# Generated by Django 2.1.5 on 2019-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
